-- ADD IS_MASTER_CERTIFICATE COLUMN TO ORGANIZATION
alter table ORGANIZATION
  add column IS_MASTER_CERTIFICATE integer;

update ORGANIZATION
set IS_MASTER_CERTIFICATE = 0;

alter table ORGANIZATION
  alter column IS_MASTER_CERTIFICATE set not null;