-- ADD IS_MASTER_CERTIFICATE COLUMN TO ORGANIZATION
alter table ORGANIZATION
  add column IS_MASTER_CERTIFICATE int4;

update ORGANIZATION
set IS_MASTER_CERTIFICATE = 0;

alter table ORGANIZATION
  alter column IS_MASTER_CERTIFICATE set not null;