package org.openfact.pe.ws.sunat.services;

import javax.activation.DataHandler;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 */
@WebService(name = "billService", targetNamespace = "http://service.sunat.gob.pe")
public interface BillService {


    /**
     * @param ticket
     * @return returns org.openfact.ubl21.pe.send.StatusResponse
     */
    @WebMethod(action = "urn:getStatus")
    @WebResult(name = "status", targetNamespace = "")
    @RequestWrapper(localName = "getStatus", targetNamespace = "http://service.sunat.gob.pe", className = "org.openfact.pe.ws.sunat.GetStatus")
    @ResponseWrapper(localName = "getStatusResponse", targetNamespace = "http://service.sunat.gob.pe", className = "org.openfact.pe.ws.sunat.GetStatusResponse")
    public StatusResponse getStatus(
            @WebParam(name = "ticket", targetNamespace = "") String ticket);

    /**
     * @param fileName
     * @param contentFile
     * @return returns byte[]
     */
    @WebMethod(action = "urn:sendBillAddress1")
    @WebResult(name = "applicationResponse", targetNamespace = "")
    @RequestWrapper(localName = "sendBillAddress1", targetNamespace = "http://service.sunat.gob.pe", className = "org.openfact.pe.ws.sunat.SendBill")
    @ResponseWrapper(localName = "sendBillResponse", targetNamespace = "http://service.sunat.gob.pe", className = "org.openfact.pe.ws.sunat.SendBillResponse")
    public byte[] sendBill(
            @WebParam(name = "fileName", targetNamespace = "") String fileName,
            @WebParam(name = "contentFile", targetNamespace = "") DataHandler contentFile);

    /**
     * @param fileName
     * @param contentFile
     * @return returns java.lang.String
     */
    @WebMethod(action = "urn:sendPack")
    @WebResult(name = "ticket", targetNamespace = "")
    @RequestWrapper(localName = "sendPack", targetNamespace = "http://service.sunat.gob.pe", className = "org.openfact.pe.ws.sunat.SendPack")
    @ResponseWrapper(localName = "sendPackResponse", targetNamespace = "http://service.sunat.gob.pe", className = "org.openfact.pe.ws.sunat.SendPackResponse")
    public String sendPack(
            @WebParam(name = "fileName", targetNamespace = "") String fileName,
            @WebParam(name = "contentFile", targetNamespace = "") DataHandler contentFile);

    /**
     * @param fileName
     * @param contentFile
     * @return returns java.lang.String
     */
    @WebMethod(action = "urn:sendSummary")
    @WebResult(name = "ticket", targetNamespace = "")
    @RequestWrapper(localName = "sendSummary", targetNamespace = "http://service.sunat.gob.pe", className = "org.openfact.pe.ws.sunat.SendSummary")
    @ResponseWrapper(localName = "sendSummaryResponse", targetNamespace = "http://service.sunat.gob.pe", className = "org.openfact.pe.ws.sunat.SendSummaryResponse")
    public String sendSummary(
            @WebParam(name = "fileName", targetNamespace = "") String fileName,
            @WebParam(name = "contentFile", targetNamespace = "") DataHandler contentFile);

}
